### PR TITLE
Function arity changes

### LINKED ISSUE #2: The rate-limited return object loses some function behavior
I'm having an issue where I rate limit an async function that accepts a callback and then I pass that rate-limited function to another library, node-stream-worker. That library [checks](https://github.com/goodeggs/stream-worker/blob/master/stream-worker.js#L9) the arity of the function and uses that to determine whether it uses async callbacks or promises. The issue arises because my original function required 2 arguments and had a `.length` of 2, but after it passes through your rate limiter, its `.length` is `undefined`.

I'm wondering if you would accept a pull request where I add some additional properties to the limiter object returned by the library to make the limiter appear to be more like a function. I'd like to implement at least `.length`, but there is a [whole world](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) of possible behaviors to implement.

### PR DESCRIPTION
**Pull request by robludwig**
Fixes #2.

I needed this for a fix of my own. It adds some helpful behavior to the object returned by the rate limiter. It's probably an edge case and not of interest to many but I found it useful.

Tests all pass.
I studied the methodology of [blakeembrey/arity](https://github.com/blakeembrey/arity) in crafting the solution.

### CODE REVIEW

**Comment by xavi-** [comment]
Hello, thanks for the PR.

Personal bias, but metaprogramming kinda creeps me out.  That said, I certainly see the value of making sure the function arity is consistent.  Perhaps we could use this technique instead?

``` js
Object.defineProperty(limiter, "length", { value: fn.length })
```

Wrote a more detailed explanation here: http://stackoverflow.com/questions/7316688/how-to-programmatically-set-the-length-of-a-function/37645357#37645357

It'd be less code and wouldn't require metaprogramming.  The down side is that this trick doesn't work in all versions of node.js which is a bummer.  We'd have to wrap the call in a try/catch to make sure we don't break people's existing code.  What do you think?

**Comment by robludwig** [comment]
I share your wariness of metaprogramming, and `defineProperty` works perfectly for my purposes. I updated the PR to use that instead and did some testing to see which versions it works for. It looks like node with version >= 3 should be fine. Otherwise it fails with a `TypeError`. I decided to just catch and discard the error since it doesn't seem hugely important if it fails.

**Comment by robludwig** [comment]
Hi-
I fixed this to use defineProperty and to check for errors when doing so. Anything else needed before merging?

**Comment by markstos** [comment]
LGTM.

**Comment by xavi-** [comment]
Sorry I dropped this on the flow.  Thank you!

**Pull request merged**
